module.exports = [
  {
    username: "bulbasaur",
    displayName: "Bulbasaur",
    userRating: 1.7,
    gender: "female",
    height: "2’04”",
    imgUrl: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
    interests: ["Grass", "Poison"],
  },
  {
    username: "ivysaur",
    displayName: "Ivysaur",
    userRating: 1.7,
    gender: "female",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/ivysaur.jpg",
    interests: ["Grass", "Poison"],
  },
  {
    username: "venusaur",
    displayName: "Venusaur",
    userRating: 1.7,
    gender: "female",
    height: "6’07”",
    imgUrl: "http://img.pokemondb.net/artwork/venusaur.jpg",
    interests: ["Grass", "Poison"],
  },
  {
    username: "charmander",
    displayName: "Charmander",
    userRating: 4.7,
    gender: "female",
    height: "2’00”",
    imgUrl: "http://img.pokemondb.net/artwork/charmander.jpg",
    interests: ["Fire"],
  },
  {
    username: "charmeleon",
    displayName: "Charmeleon",
    userRating: 4.7,
    gender: "male",
    height: "3’07”",
    imgUrl: "http://img.pokemondb.net/artwork/charmeleon.jpg",
    interests: ["Fire"],
  },
  {
    username: "charizard",
    displayName: "Charizard",
    userRating: 4.7,
    gender: "female",
    height: "5’07”",
    imgUrl: "http://img.pokemondb.net/artwork/charizard.jpg",
    interests: ["Fire", "Flying"],
  },
  {
    username: "squirtle",
    displayName: "Squirtle",
    userRating: 2.2,
    gender: "female",
    height: "1’08”",
    imgUrl: "http://img.pokemondb.net/artwork/squirtle.jpg",
    interests: ["Water"],
  },
  {
    username: "wartortle",
    displayName: "Wartortle",
    userRating: 2.2,
    gender: "female",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/wartortle.jpg",
    interests: ["Water"],
  },
  {
    username: "blastoise",
    displayName: "Blastoise",
    userRating: 2.2,
    gender: "female",
    height: "5’03”",
    imgUrl: "http://img.pokemondb.net/artwork/blastoise.jpg",
    interests: ["Water"],
  },
  {
    username: "caterpie",
    displayName: "Caterpie",
    userRating: 2.5,
    gender: "female",
    height: "1’00”",
    imgUrl: "http://img.pokemondb.net/artwork/caterpie.jpg",
    interests: ["Bug"],
  },
  {
    username: "metapod",
    displayName: "Metapod",
    userRating: 3.05,
    gender: "male",
    height: "2’04”",
    imgUrl: "http://img.pokemondb.net/artwork/metapod.jpg",
    interests: ["Bug"],
  },
  {
    username: "butterfree",
    displayName: "Butterfree",
    userRating: 5.5,
    gender: "male",
    height: "3’07”",
    imgUrl: "http://img.pokemondb.net/artwork/butterfree.jpg",
    interests: ["Bug", "Flying"],
  },
  {
    username: "weedle",
    displayName: "Weedle",
    userRating: 2.5,
    gender: "male",
    height: "1’00”",
    imgUrl: "http://img.pokemondb.net/artwork/weedle.jpg",
    interests: ["Bug", "Poison"],
  },
  {
    username: "kakuna",
    displayName: "Kakuna",
    userRating: 3.05,
    gender: "male",
    height: "2’00”",
    imgUrl: "http://img.pokemondb.net/artwork/kakuna.jpg",
    interests: ["Bug", "Poison"],
  },
  {
    username: "beedrill",
    displayName: "Beedrill",
    userRating: 4.85,
    gender: "male",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/beedrill.jpg",
    interests: ["Bug", "Poison"],
  },
  {
    username: "pidgey",
    displayName: "Pidgey",
    userRating: 7.25,
    gender: "male",
    height: "1’00”",
    imgUrl: "http://img.pokemondb.net/artwork/pidgey.jpg",
    interests: ["Normal", "Flying"],
  },
  {
    username: "pidgeotto",
    displayName: "Pidgeotto",
    userRating: 7.25,
    gender: "male",
    height: "3’07”",
    imgUrl: "http://img.pokemondb.net/artwork/pidgeotto.jpg",
    interests: ["Normal", "Flying"],
  },
  {
    username: "pidgeot",
    displayName: "Pidgeot",
    userRating: 7.25,
    gender: "female",
    height: "4’11”",
    imgUrl: "http://img.pokemondb.net/artwork/pidgeot.jpg",
    interests: ["Normal", "Flying"],
  },
  {
    username: "rattata",
    displayName: "Rattata",
    userRating: 2.75,
    gender: "female",
    height: "1’00”",
    imgUrl: "http://img.pokemondb.net/artwork/rattata.jpg",
    interests: ["Normal"],
  },
  {
    username: "raticate",
    displayName: "Raticate",
    userRating: 2.75,
    gender: "male",
    height: "2’04”",
    imgUrl: "http://img.pokemondb.net/artwork/raticate.jpg",
    interests: ["Normal"],
  },
  {
    username: "spearow",
    displayName: "Spearow",
    userRating: 4.85,
    gender: "female",
    height: "1’00”",
    imgUrl: "http://img.pokemondb.net/artwork/spearow.jpg",
    interests: ["Normal", "Flying"],
  },
  {
    username: "fearow",
    displayName: "Fearow",
    userRating: 4.85,
    gender: "female",
    height: "3’11”",
    imgUrl: "http://img.pokemondb.net/artwork/fearow.jpg",
    interests: ["Normal", "Flying"],
  },
  {
    username: "ekans",
    displayName: "Ekans",
    userRating: 6.35,
    gender: "male",
    height: "6’07”",
    imgUrl: "http://img.pokemondb.net/artwork/ekans.jpg",
    interests: ["Poison"],
  },
  {
    username: "arbok",
    displayName: "Arbok",
    userRating: 6.35,
    gender: "male",
    height: "11’06”",
    imgUrl: "http://img.pokemondb.net/artwork/arbok.jpg",
    interests: ["Poison"],
  },
  {
    username: "pikachu",
    displayName: "Pikachu",
    userRating: 1.55,
    gender: "male",
    height: "1’04”",
    imgUrl: "http://img.pokemondb.net/artwork/pikachu.jpg",
    interests: ["Electric"],
  },
  {
    username: "raichu",
    displayName: "Raichu",
    userRating: 1.55,
    gender: "female",
    height: "2’07”",
    imgUrl: "http://img.pokemondb.net/artwork/raichu.jpg",
    interests: ["Electric"],
  },
  {
    username: "sandshrew",
    displayName: "Sandshrew",
    userRating: 7.3,
    gender: "male",
    height: "2’00”",
    imgUrl: "http://img.pokemondb.net/artwork/sandshrew.jpg",
    interests: ["Ground"],
  },
  {
    username: "sandslash",
    displayName: "Sandslash",
    userRating: 7.3,
    gender: "female",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/sandslash.jpg",
    interests: ["Ground"],
  },
  {
    username: "nidoran-f",
    displayName: "Nidoran",
    userRating: 2.75,
    gender: "male",
    height: "1’04”",
    imgUrl: "https://img.pokemondb.net/artwork/nidoran-f.jpg",
    interests: ["Poison"],
  },
  {
    username: "nidorina",
    displayName: "Nidorina",
    userRating: 2.75,
    gender: "male",
    height: "2’07”",
    imgUrl: "http://img.pokemondb.net/artwork/nidorina.jpg",
    interests: ["Poison"],
  },
  {
    username: "nidoqueen",
    displayName: "Nidoqueen",
    userRating: 6.25,
    gender: "male",
    height: "4’03”",
    imgUrl: "http://img.pokemondb.net/artwork/nidoqueen.jpg",
    interests: ["Poison", "Ground"],
  },
  {
    username: "nidoran-m",
    displayName: "Nidoran",
    userRating: 2.75,
    gender: "female",
    height: "1’08”",
    imgUrl: "https://img.pokemondb.net/artwork/nidoran-m.jpg",
    interests: ["Poison"],
  },
  {
    username: "nidorino",
    displayName: "Nidorino",
    userRating: 2.75,
    gender: "female",
    height: "2’11”",
    imgUrl: "http://img.pokemondb.net/artwork/nidorino.jpg",
    interests: ["Poison"],
  },
  {
    username: "nidoking",
    displayName: "Nidoking",
    userRating: 6.25,
    gender: "female",
    height: "4’07”",
    imgUrl: "http://img.pokemondb.net/artwork/nidoking.jpg",
    interests: ["Poison", "Ground"],
  },
  {
    username: "clefairy",
    displayName: "Clefairy",
    userRating: 6.6,
    gender: "male",
    height: "2’00”",
    imgUrl: "http://img.pokemondb.net/artwork/clefairy.jpg",
    interests: ["Normal"],
  },
  {
    username: "clefable",
    displayName: "Clefable",
    userRating: 5.45,
    gender: "male",
    height: "4’03”",
    imgUrl: "http://img.pokemondb.net/artwork/clefable.jpg",
    interests: ["Normal"],
  },
  {
    username: "vulpix",
    displayName: "Vulpix",
    userRating: 3.5,
    gender: "male",
    height: "2’00”",
    imgUrl: "http://img.pokemondb.net/artwork/vulpix.jpg",
    interests: ["Fire"],
  },
  {
    username: "ninetales",
    displayName: "Ninetales",
    userRating: 3.5,
    gender: "male",
    height: "3’07”",
    imgUrl: "http://img.pokemondb.net/artwork/ninetales.jpg",
    interests: ["Fire"],
  },
  {
    username: "jigglypuff",
    displayName: "Jigglypuff",
    userRating: 6.6,
    gender: "female",
    height: "1’08”",
    imgUrl: "http://img.pokemondb.net/artwork/jigglypuff.jpg",
    interests: ["Normal"],
  },
  {
    username: "wigglytuff",
    displayName: "Wigglytuff",
    userRating: 5.95,
    gender: "female",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/wigglytuff.jpg",
    interests: ["Normal"],
  },
  {
    username: "zubat",
    displayName: "Zubat",
    userRating: 7.55,
    gender: "female",
    height: "2’07”",
    imgUrl: "http://img.pokemondb.net/artwork/zubat.jpg",
    interests: ["Poison", "Flying"],
  },
  {
    username: "golbat",
    displayName: "Golbat",
    userRating: 7.55,
    gender: "male",
    height: "5’03”",
    imgUrl: "http://img.pokemondb.net/artwork/golbat.jpg",
    interests: ["Poison", "Flying"],
  },
  {
    username: "oddish",
    displayName: "Oddish",
    userRating: 2.5,
    gender: "female",
    height: "1’08”",
    imgUrl: "http://img.pokemondb.net/artwork/oddish.jpg",
    interests: ["Grass", "Poison"],
  },
  {
    username: "gloom",
    displayName: "Gloom",
    userRating: 0.05,
    gender: "male",
    height: "2’07”",
    imgUrl: "http://img.pokemondb.net/artwork/gloom.jpg",
    interests: ["Grass", "Poison"],
  },
  {
    username: "vileplume",
    displayName: "Vileplume",
    userRating: 1.35,
    gender: "female",
    height: "3’11”",
    imgUrl: "http://img.pokemondb.net/artwork/vileplume.jpg",
    interests: ["Grass", "Poison"],
  },
  {
    username: "paras",
    displayName: "Paras",
    userRating: 0.3,
    gender: "female",
    height: "1’00”",
    imgUrl: "http://img.pokemondb.net/artwork/paras.jpg",
    interests: ["Bug", "Grass"],
  },
  {
    username: "parasect",
    displayName: "Parasect",
    userRating: 0.3,
    gender: "female",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/parasect.jpg",
    interests: ["Bug", "Grass"],
  },
  {
    username: "venonat",
    displayName: "Venonat",
    userRating: 2.5,
    gender: "male",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/venonat.jpg",
    interests: ["Bug", "Poison"],
  },
  {
    username: "venomoth",
    displayName: "Venomoth",
    userRating: 7.35,
    gender: "male",
    height: "4’11”",
    imgUrl: "http://img.pokemondb.net/artwork/venomoth.jpg",
    interests: ["Bug", "Poison"],
  },
  {
    username: "diglett",
    displayName: "Diglett",
    userRating: 7.95,
    gender: "male",
    height: "0’08”",
    imgUrl: "http://img.pokemondb.net/artwork/diglett.jpg",
    interests: ["Ground"],
  },
  {
    username: "dugtrio",
    displayName: "Dugtrio",
    userRating: 7.95,
    gender: "female",
    height: "2’04”",
    imgUrl: "http://img.pokemondb.net/artwork/dugtrio.jpg",
    interests: ["Ground"],
  },
  {
    username: "meowth",
    displayName: "Meowth",
    userRating: 6.35,
    gender: "female",
    height: "1’04”",
    imgUrl: "http://img.pokemondb.net/artwork/meowth.jpg",
    interests: ["Normal"],
  },
  {
    username: "persian",
    displayName: "Persian",
    userRating: 6.35,
    gender: "female",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/persian.jpg",
    interests: ["Normal"],
  },
  {
    username: "psyduck",
    displayName: "Psyduck",
    userRating: 1.65,
    gender: "female",
    height: "2’07”",
    imgUrl: "http://img.pokemondb.net/artwork/psyduck.jpg",
    interests: ["Water"],
  },
  {
    username: "golduck",
    displayName: "Golduck",
    userRating: 1.65,
    gender: "male",
    height: "5’07”",
    imgUrl: "http://img.pokemondb.net/artwork/golduck.jpg",
    interests: ["Water"],
  },
  {
    username: "mankey",
    displayName: "Mankey",
    userRating: 6.4,
    gender: "female",
    height: "1’08”",
    imgUrl: "http://img.pokemondb.net/artwork/mankey.jpg",
    interests: ["Fighting"],
  },
  {
    username: "primeape",
    displayName: "Primeape",
    userRating: 6.4,
    gender: "male",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/primeape.jpg",
    interests: ["Fighting"],
  },
  {
    username: "growlithe",
    displayName: "Growlithe",
    userRating: 7.7,
    gender: "female",
    height: "2’04”",
    imgUrl: "http://img.pokemondb.net/artwork/growlithe.jpg",
    interests: ["Fire"],
  },
  {
    username: "arcanine",
    displayName: "Arcanine",
    userRating: 7.7,
    gender: "female",
    height: "6’03”",
    imgUrl: "http://img.pokemondb.net/artwork/arcanine.jpg",
    interests: ["Fire"],
  },
  {
    username: "poliwag",
    displayName: "Poliwag",
    userRating: 1.65,
    gender: "female",
    height: "2’00”",
    imgUrl: "http://img.pokemondb.net/artwork/poliwag.jpg",
    interests: ["Water"],
  },
  {
    username: "poliwhirl",
    displayName: "Poliwhirl",
    userRating: 1.65,
    gender: "male",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/poliwhirl.jpg",
    interests: ["Water"],
  },
  {
    username: "poliwrath",
    displayName: "Poliwrath",
    userRating: 1.65,
    gender: "female",
    height: "4’03”",
    imgUrl: "http://img.pokemondb.net/artwork/poliwrath.jpg",
    interests: ["Water", "Fighting"],
  },
  {
    username: "abra",
    displayName: "Abra",
    userRating: 4.9,
    gender: "female",
    height: "2’11”",
    imgUrl: "http://img.pokemondb.net/artwork/abra.jpg",
    interests: ["Psychic"],
  },
  {
    username: "kadabra",
    displayName: "Kadabra",
    userRating: 4.9,
    gender: "female",
    height: "4’03”",
    imgUrl: "http://img.pokemondb.net/artwork/kadabra.jpg",
    interests: ["Psychic"],
  },
  {
    username: "alakazam",
    displayName: "Alakazam",
    userRating: 4.9,
    gender: "female",
    height: "4’11”",
    imgUrl: "http://img.pokemondb.net/artwork/alakazam.jpg",
    interests: ["Psychic"],
  },
  {
    username: "machop",
    displayName: "Machop",
    userRating: 4,
    gender: "female",
    height: "2’07”",
    imgUrl: "http://img.pokemondb.net/artwork/machop.jpg",
    interests: ["Fighting"],
  },
  {
    username: "machoke",
    displayName: "Machoke",
    userRating: 4,
    gender: "female",
    height: "4’11”",
    imgUrl: "http://img.pokemondb.net/artwork/machoke.jpg",
    interests: ["Fighting"],
  },
  {
    username: "machamp",
    displayName: "Machamp",
    userRating: 4,
    gender: "female",
    height: "5’03”",
    imgUrl: "http://img.pokemondb.net/artwork/machamp.jpg",
    interests: ["Fighting"],
  },
  {
    username: "bellsprout",
    displayName: "Bellsprout",
    userRating: 4.1,
    gender: "female",
    height: "2’04”",
    imgUrl: "http://img.pokemondb.net/artwork/bellsprout.jpg",
    interests: ["Grass", "Poison"],
  },
  {
    username: "weepinbell",
    displayName: "Weepinbell",
    userRating: 4.1,
    gender: "male",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/weepinbell.jpg",
    interests: ["Grass", "Poison"],
  },
  {
    username: "victreebel",
    displayName: "Victreebel",
    userRating: 4.1,
    gender: "female",
    height: "5’07”",
    imgUrl: "http://img.pokemondb.net/artwork/victreebel.jpg",
    interests: ["Grass", "Poison"],
  },
  {
    username: "tentacool",
    displayName: "Tentacool",
    userRating: 2.2,
    gender: "female",
    height: "2’11”",
    imgUrl: "http://img.pokemondb.net/artwork/tentacool.jpg",
    interests: ["Water", "Poison"],
  },
  {
    username: "tentacruel",
    displayName: "Tentacruel",
    userRating: 2.2,
    gender: "female",
    height: "5’03”",
    imgUrl: "http://img.pokemondb.net/artwork/tentacruel.jpg",
    interests: ["Water", "Poison"],
  },
  {
    username: "geodude",
    displayName: "Geodude",
    userRating: 0.4,
    gender: "female",
    height: "1’04”",
    imgUrl: "http://img.pokemondb.net/artwork/geodude.jpg",
    interests: ["Rock", "Ground"],
  },
  {
    username: "graveler",
    displayName: "Graveler",
    userRating: 0.4,
    gender: "female",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/graveler.jpg",
    interests: ["Rock", "Ground"],
  },
  {
    username: "golem",
    displayName: "Golem",
    userRating: 0.4,
    gender: "female",
    height: "4’07”",
    imgUrl: "http://img.pokemondb.net/artwork/golem.jpg",
    interests: ["Rock", "Ground"],
  },
  {
    username: "ponyta",
    displayName: "Ponyta",
    userRating: 2.45,
    gender: "female",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/ponyta.jpg",
    interests: ["Fire"],
  },
  {
    username: "rapidash",
    displayName: "Rapidash",
    userRating: 2.45,
    gender: "female",
    height: "5’07”",
    imgUrl: "http://img.pokemondb.net/artwork/rapidash.jpg",
    interests: ["Fire"],
  },
  {
    username: "slowpoke",
    displayName: "Slowpoke",
    userRating: 7.2,
    gender: "male",
    height: "3’11”",
    imgUrl: "http://img.pokemondb.net/artwork/slowpoke.jpg",
    interests: ["Water", "Psychic"],
  },
  {
    username: "slowbro",
    displayName: "Slowbro",
    userRating: 7.2,
    gender: "male",
    height: "5’03”",
    imgUrl: "http://img.pokemondb.net/artwork/slowbro.jpg",
    interests: ["Water", "Psychic"],
  },
  {
    username: "magnemite",
    displayName: "Magnemite",
    userRating: 7.4,
    gender: "male",
    height: "1’00”",
    imgUrl: "http://img.pokemondb.net/artwork/magnemite.jpg",
    interests: ["Electric", "Steel"],
  },
  {
    username: "magneton",
    displayName: "Magneton",
    userRating: 7.4,
    gender: "male",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/magneton.jpg",
    interests: ["Electric", "Steel"],
  },
  {
    username: "farfetch'd",
    displayName: "Farfetch'd",
    userRating: 6.4,
    gender: "female",
    height: "2’07”",
    imgUrl: "http://img.pokemondb.net/artwork/farfetchd.jpg",
    interests: ["Normal", "Flying"],
  },
  {
    username: "doduo",
    displayName: "Doduo",
    userRating: 3.85,
    gender: "male",
    height: "4’07”",
    imgUrl: "http://img.pokemondb.net/artwork/doduo.jpg",
    interests: ["Normal", "Flying"],
  },
  {
    username: "dodrio",
    displayName: "Dodrio",
    userRating: 3.85,
    gender: "female",
    height: "5’11”",
    imgUrl: "http://img.pokemondb.net/artwork/dodrio.jpg",
    interests: ["Normal", "Flying"],
  },
  {
    username: "seel",
    displayName: "Seel",
    userRating: 5.75,
    gender: "male",
    height: "3’07”",
    imgUrl: "http://img.pokemondb.net/artwork/seel.jpg",
    interests: ["Water"],
  },
  {
    username: "dewgong",
    displayName: "Dewgong",
    userRating: 5.75,
    gender: "male",
    height: "5’07”",
    imgUrl: "http://img.pokemondb.net/artwork/dewgong.jpg",
    interests: ["Water", "Ice"],
  },
  {
    username: "grimer",
    displayName: "Grimer",
    userRating: 7.15,
    gender: "male",
    height: "2’11”",
    imgUrl: "http://img.pokemondb.net/artwork/grimer.jpg",
    interests: ["Poison"],
  },
  {
    username: "muk",
    displayName: "Muk",
    userRating: 7.15,
    gender: "female",
    height: "3’11”",
    imgUrl: "http://img.pokemondb.net/artwork/muk.jpg",
    interests: ["Poison"],
  },
  {
    username: "shellder",
    displayName: "Shellder",
    userRating: 7.1,
    gender: "female",
    height: "1’00”",
    imgUrl: "http://img.pokemondb.net/artwork/shellder.jpg",
    interests: ["Water"],
  },
  {
    username: "cloyster",
    displayName: "Cloyster",
    userRating: 7.1,
    gender: "female",
    height: "4’11”",
    imgUrl: "http://img.pokemondb.net/artwork/cloyster.jpg",
    interests: ["Water", "Ice"],
  },
  {
    username: "gastly",
    displayName: "Gastly",
    userRating: 0,
    gender: "male",
    height: "4’03”",
    imgUrl: "http://img.pokemondb.net/artwork/gastly.jpg",
    interests: ["Ghost", "Poison"],
  },
  {
    username: "haunter",
    displayName: "Haunter",
    userRating: 0,
    gender: "male",
    height: "5’03”",
    imgUrl: "http://img.pokemondb.net/artwork/haunter.jpg",
    interests: ["Ghost", "Poison"],
  },
  {
    username: "gengar",
    displayName: "Gengar",
    userRating: 0,
    gender: "male",
    height: "4’11”",
    imgUrl: "http://img.pokemondb.net/artwork/gengar.jpg",
    interests: ["Ghost", "Poison"],
  },
  {
    username: "onix",
    displayName: "Onix",
    userRating: 6.65,
    gender: "female",
    height: "28’10”",
    imgUrl: "http://img.pokemondb.net/artwork/onix.jpg",
    interests: ["Rock", "Ground"],
  },
  {
    username: "drowzee",
    displayName: "Drowzee",
    userRating: 1.95,
    gender: "female",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/drowzee.jpg",
    interests: ["Psychic"],
  },
  {
    username: "hypno",
    displayName: "Hypno",
    userRating: 1.95,
    gender: "female",
    height: "5’03”",
    imgUrl: "http://img.pokemondb.net/artwork/hypno.jpg",
    interests: ["Psychic"],
  },
  {
    username: "krabby",
    displayName: "Krabby",
    userRating: 6.25,
    gender: "male",
    height: "1’04”",
    imgUrl: "http://img.pokemondb.net/artwork/krabby.jpg",
    interests: ["Water"],
  },
  {
    username: "kingler",
    displayName: "Kingler",
    userRating: 6.25,
    gender: "female",
    height: "4’03”",
    imgUrl: "http://img.pokemondb.net/artwork/kingler.jpg",
    interests: ["Water"],
  },
  {
    username: "voltorb",
    displayName: "Voltorb",
    userRating: 5.3,
    gender: "male",
    height: "1’08”",
    imgUrl: "http://img.pokemondb.net/artwork/voltorb.jpg",
    interests: ["Electric"],
  },
  {
    username: "electrode",
    displayName: "Electrode",
    userRating: 5.3,
    gender: "male",
    height: "3’11”",
    imgUrl: "http://img.pokemondb.net/artwork/electrode.jpg",
    interests: ["Electric"],
  },
  {
    username: "exeggcute",
    displayName: "Exeggcute",
    userRating: 6.95,
    gender: "female",
    height: "1’04”",
    imgUrl: "http://img.pokemondb.net/artwork/exeggcute.jpg",
    interests: ["Grass", "Psychic"],
  },
  {
    username: "exeggutor",
    displayName: "Exeggutor",
    userRating: 6.95,
    gender: "male",
    height: "6’07”",
    imgUrl: "http://img.pokemondb.net/artwork/exeggutor.jpg",
    interests: ["Grass", "Psychic"],
  },
  {
    username: "cubone",
    displayName: "Cubone",
    userRating: 0.2,
    gender: "male",
    height: "1’04”",
    imgUrl: "http://img.pokemondb.net/artwork/cubone.jpg",
    interests: ["Ground"],
  },
  {
    username: "marowak",
    displayName: "Marowak",
    userRating: 0.2,
    gender: "male",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/marowak.jpg",
    interests: ["Ground"],
  },
  {
    username: "hitmonlee",
    displayName: "Hitmonlee",
    userRating: 4.2,
    gender: "female",
    height: "4’11”",
    imgUrl: "http://img.pokemondb.net/artwork/hitmonlee.jpg",
    interests: ["Fighting"],
  },
  {
    username: "hitmonchan",
    displayName: "Hitmonchan",
    userRating: 1.95,
    gender: "female",
    height: "4’07”",
    imgUrl: "http://img.pokemondb.net/artwork/hitmonchan.jpg",
    interests: ["Fighting"],
  },
  {
    username: "lickitung",
    displayName: "Lickitung",
    userRating: 0.65,
    gender: "female",
    height: "3’11”",
    imgUrl: "http://img.pokemondb.net/artwork/lickitung.jpg",
    interests: ["Normal"],
  },
  {
    username: "koffing",
    displayName: "Koffing",
    userRating: 0,
    gender: "male",
    height: "2’00”",
    imgUrl: "http://img.pokemondb.net/artwork/koffing.jpg",
    interests: ["Poison"],
  },
  {
    username: "weezing",
    displayName: "Weezing",
    userRating: 0,
    gender: "female",
    height: "3’11”",
    imgUrl: "http://img.pokemondb.net/artwork/weezing.jpg",
    interests: ["Poison"],
  },
  {
    username: "rhyhorn",
    displayName: "Rhyhorn",
    userRating: 6,
    gender: "male",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/rhyhorn.jpg",
    interests: ["Ground", "Rock"],
  },
  {
    username: "rhydon",
    displayName: "Rhydon",
    userRating: 6,
    gender: "female",
    height: "6’03”",
    imgUrl: "http://img.pokemondb.net/artwork/rhydon.jpg",
    interests: ["Ground", "Rock"],
  },
  {
    username: "chansey",
    displayName: "Chansey",
    userRating: 6.55,
    gender: "male",
    height: "3’07”",
    imgUrl: "http://img.pokemondb.net/artwork/chansey.jpg",
    interests: ["Normal"],
  },
  {
    username: "tangela",
    displayName: "Tangela",
    userRating: 7.2,
    gender: "female",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/tangela.jpg",
    interests: ["Grass"],
  },
  {
    username: "kangaskhan",
    displayName: "Kangaskhan",
    userRating: 1.95,
    gender: "male",
    height: "7’03”",
    imgUrl: "http://img.pokemondb.net/artwork/kangaskhan.jpg",
    interests: ["Normal"],
  },
  {
    username: "horsea",
    displayName: "Horsea",
    userRating: 0.3,
    gender: "male",
    height: "1’04”",
    imgUrl: "http://img.pokemondb.net/artwork/horsea.jpg",
    interests: ["Water"],
  },
  {
    username: "seadra",
    displayName: "Seadra",
    userRating: 0.3,
    gender: "female",
    height: "3’11”",
    imgUrl: "http://img.pokemondb.net/artwork/seadra.jpg",
    interests: ["Water"],
  },
  {
    username: "goldeen",
    displayName: "Goldeen",
    userRating: 1.55,
    gender: "male",
    height: "2’00”",
    imgUrl: "http://img.pokemondb.net/artwork/goldeen.jpg",
    interests: ["Water"],
  },
  {
    username: "seaking",
    displayName: "Seaking",
    userRating: 1.55,
    gender: "male",
    height: "4’03”",
    imgUrl: "http://img.pokemondb.net/artwork/seaking.jpg",
    interests: ["Water"],
  },
  {
    username: "staryu",
    displayName: "Staryu",
    userRating: 7.4,
    gender: "male",
    height: "2’07”",
    imgUrl: "http://img.pokemondb.net/artwork/staryu.jpg",
    interests: ["Water"],
  },
  {
    username: "starmie",
    displayName: "Starmie",
    userRating: 7.4,
    gender: "male",
    height: "3’07”",
    imgUrl: "http://img.pokemondb.net/artwork/starmie.jpg",
    interests: ["Water", "Psychic"],
  },
  {
    username: "mr. mime",
    displayName: "Mr. Mime",
    userRating: 5.05,
    gender: "male",
    height: "4’03”",
    imgUrl: "https://img.pokemondb.net/artwork/mr-mime.jpg",
    interests: ["Psychic"],
  },
  {
    username: "scyther",
    displayName: "Scyther",
    userRating: 4,
    gender: "female",
    height: "4’11”",
    imgUrl: "http://img.pokemondb.net/artwork/scyther.jpg",
    interests: ["Bug", "Flying"],
  },
  {
    username: "jynx",
    displayName: "Jynx",
    userRating: 4.35,
    gender: "male",
    height: "4’07”",
    imgUrl: "http://img.pokemondb.net/artwork/jynx.jpg",
    interests: ["Ice", "Psychic"],
  },
  {
    username: "electabuzz",
    displayName: "Electabuzz",
    userRating: 3.6,
    gender: "female",
    height: "3’07”",
    imgUrl: "http://img.pokemondb.net/artwork/electabuzz.jpg",
    interests: ["Electric"],
  },
  {
    username: "magmar",
    displayName: "Magmar",
    userRating: 3.6,
    gender: "female",
    height: "4’03”",
    imgUrl: "http://img.pokemondb.net/artwork/magmar.jpg",
    interests: ["Fire"],
  },
  {
    username: "pinsir",
    displayName: "Pinsir",
    userRating: 7.65,
    gender: "male",
    height: "4’11”",
    imgUrl: "http://img.pokemondb.net/artwork/pinsir.jpg",
    interests: ["Bug"],
  },
  {
    username: "tauros",
    displayName: "Tauros",
    userRating: 6.25,
    gender: "female",
    height: "4’07”",
    imgUrl: "http://img.pokemondb.net/artwork/tauros.jpg",
    interests: ["Normal"],
  },
  {
    username: "magikarp",
    displayName: "Magikarp",
    userRating: 7.75,
    gender: "female",
    height: "2’11”",
    imgUrl: "http://img.pokemondb.net/artwork/magikarp.jpg",
    interests: ["Water"],
  },
  {
    username: "gyarados",
    displayName: "Gyarados",
    userRating: 7.65,
    gender: "female",
    height: "21’04”",
    imgUrl: "http://img.pokemondb.net/artwork/gyarados.jpg",
    interests: ["Water", "Flying"],
  },
  {
    username: "lapras",
    displayName: "Lapras",
    userRating: 4.65,
    gender: "female",
    height: "8’02”",
    imgUrl: "http://img.pokemondb.net/artwork/lapras.jpg",
    interests: ["Water", "Ice"],
  },
  {
    username: "ditto",
    displayName: "Ditto",
    userRating: 7.5,
    gender: "male",
    height: "1’00”",
    imgUrl: "http://img.pokemondb.net/artwork/ditto.jpg",
    interests: ["Normal"],
  },
  {
    username: "eevee",
    displayName: "Eevee",
    userRating: 5.35,
    gender: "female",
    height: "1’00”",
    imgUrl: "http://img.pokemondb.net/artwork/eevee.jpg",
    interests: ["Normal"],
  },
  {
    username: "vaporeon",
    displayName: "Vaporeon",
    userRating: 4.65,
    gender: "female",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/vaporeon.jpg",
    interests: ["Water"],
  },
  {
    username: "jolteon",
    displayName: "Jolteon",
    userRating: 4.75,
    gender: "female",
    height: "2’07”",
    imgUrl: "http://img.pokemondb.net/artwork/jolteon.jpg",
    interests: ["Electric"],
  },
  {
    username: "flareon",
    displayName: "Flareon",
    userRating: 3.1,
    gender: "female",
    height: "2’11”",
    imgUrl: "http://img.pokemondb.net/artwork/flareon.jpg",
    interests: ["Fire"],
  },
  {
    username: "porygon",
    displayName: "Porygon",
    userRating: 7.4,
    gender: "male",
    height: "2’07”",
    imgUrl: "http://img.pokemondb.net/artwork/porygon.jpg",
    interests: ["Normal"],
  },
  {
    username: "omanyte",
    displayName: "Omanyte",
    userRating: 6.65,
    gender: "male",
    height: "1’04”",
    imgUrl: "http://img.pokemondb.net/artwork/omanyte.jpg",
    interests: ["Rock", "Water"],
  },
  {
    username: "omastar",
    displayName: "Omastar",
    userRating: 6.65,
    gender: "male",
    height: "3’03”",
    imgUrl: "http://img.pokemondb.net/artwork/omastar.jpg",
    interests: ["Rock", "Water"],
  },
  {
    username: "kabuto",
    displayName: "Kabuto",
    userRating: 6.65,
    gender: "male",
    height: "1’08”",
    imgUrl: "http://img.pokemondb.net/artwork/kabuto.jpg",
    interests: ["Rock", "Water"],
  },
  {
    username: "kabutops",
    displayName: "Kabutops",
    userRating: 6.65,
    gender: "female",
    height: "4’03”",
    imgUrl: "http://img.pokemondb.net/artwork/kabutops.jpg",
    interests: ["Rock", "Water"],
  },
  {
    username: "aerodactyl",
    displayName: "Aerodactyl",
    userRating: 6.35,
    gender: "female",
    height: "5’11”",
    imgUrl: "http://img.pokemondb.net/artwork/aerodactyl.jpg",
    interests: ["Rock", "Flying"],
  },
  {
    username: "snorlax",
    displayName: "Snorlax",
    userRating: 4.1,
    gender: "female",
    height: "6’11”",
    imgUrl: "http://img.pokemondb.net/artwork/snorlax.jpg",
    interests: ["Normal"],
  },
  {
    username: "articuno",
    displayName: "Articuno",
    userRating: 4.05,
    gender: "male",
    height: "5’07”",
    imgUrl: "http://img.pokemondb.net/artwork/articuno.jpg",
    interests: ["Ice", "Flying"],
  },
  {
    username: "zapdos",
    displayName: "Zapdos",
    userRating: 1.55,
    gender: "male",
    height: "5’03”",
    imgUrl: "http://img.pokemondb.net/artwork/zapdos.jpg",
    interests: ["Electric", "Flying"],
  },
  {
    username: "moltres",
    displayName: "Moltres",
    userRating: 2.45,
    gender: "male",
    height: "6’07”",
    imgUrl: "http://img.pokemondb.net/artwork/moltres.jpg",
    interests: ["Fire", "Flying"],
  },
  {
    username: "dratini",
    displayName: "Dratini",
    userRating: 3.15,
    gender: "female",
    height: "5’11”",
    imgUrl: "http://img.pokemondb.net/artwork/dratini.jpg",
    interests: ["Dragon"],
  },
  {
    username: "dragonair",
    displayName: "Dragonair",
    userRating: 3.15,
    gender: "male",
    height: "13’01”",
    imgUrl: "http://img.pokemondb.net/artwork/dragonair.jpg",
    interests: ["Dragon"],
  },
  {
    username: "dragonite",
    displayName: "Dragonite",
    userRating: 6.8,
    gender: "female",
    height: "7’03”",
    imgUrl: "http://img.pokemondb.net/artwork/dragonite.jpg",
    interests: ["Dragon", "Flying"],
  },
  {
    username: "mewtwo",
    displayName: "Mewtwo",
    userRating: 6.35,
    gender: "male",
    height: "6’07”",
    imgUrl: "http://img.pokemondb.net/artwork/mewtwo.jpg",
    interests: ["Psychic"],
  },
  {
    username: "mew",
    displayName: "Mew",
    userRating: 0,
    gender: "male",
    height: "1’04”",
    imgUrl: "http://img.pokemondb.net/artwork/mew.jpg",
    interests: ["Psychic"],
  },
];
